config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  resources :posts
  resources :user_profile
  devise_for :users
  root to: 'posts#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :body, length: { maximum: 120}, allow_blank: false

end

app/models/user.rb
class User < ApplicationRecord
has_person_name

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  validates_uniqueness_of :username
  has_one_attached :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username, :profile_image])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update]
  def index
    @post = Post.new
    @posts = Post.all.order(created_at: :desc)
    end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path }
        format.turbo_stream { render turbo_stream: turbo_stream.prepend("posts", partial: "views/posts/post", locals: { post: @post }) }
      else
        format.html do 
          flash[:post_errors] = @post.errors.full_messages
          redirect_to root_path
        end
      end
    end
  end
    

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    respond_to do |format|
      if @post.destroy
        format.html { redirect_to root_path }
        format.turbo_stream { render turbo_stream: turbo_stream.remove("posts", partial: "views/posts/post", locals: { post: @post }) }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to root_path }
        format.turbo_stream { render turbo_stream: turbo_stream.replace("posts", partial: "views/posts/post", locals: { post: @post }) }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end
  private

  def post_params
    params.require(:post).permit(:body)
  end

  def set_post
    @post = current_user.posts.find(params[:id])
  end
end

app/controllers/user_profile_controller.rb
class UserProfileController < ApplicationController

    def show
        @profile = User.find(params[:id])
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_classes(flash_type)
    flash_base = "px-2 py-4 mx-auto font-sans font-medium text-center text-white"
    {
      notice: "bg-indigo-600 #{flash_base}",
      error:  "bg-red-600 #{flash_base}",
      alert: "bg-red-600 #{flash_base}"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def nav_classes
    ["devise/registrations", "devise/sessions", "devise/confirmations", "devise/passwords", "devise/unlocks"].include?(params[:controller]) ? "hidden" : nil
  end

  def label_class(options={})
    "block mb-1 font-normal leading-normal #{options[:extended_classes]}"
  end

  def input_class(options={})
    "rounded border border-gray-300 block w-full focus:outline-none focus:border-gray-400 outline-none focus-within:outline-none focus:ring-2 focus:ring-gray-200 #{options[:extended_classes]}"
  end

  def checkbox_class(options={})
    "rounded border-gray-300 border focus:ring-2 focus:ring-gray-200 text-blue-500 mr-1 #{options[:extended_classes]}"
  end

  def link_class(options={})
    "text-gray-700 underline hover:no-underline hover:text-gray-800 block #{options[:extended_classes]}"
  end

  def button_class(options={})

    variant = options[:variant]
    theme = options[:theme]

    style_button(variant, theme_button(theme))
  end

  def theme_button(theme)
    themes = {
      primary: "primary",
      secondary: "secondary",
      transparent: "transparent",
      dark: "dark"
    }

    case theme
    when themes[:primary]
      "bg-indigo-600 hover:bg-indigo-700 text-white"
    when themes[:secondary]
      "bg-teal-600 hover:bg-teal-700 text-white"
    when themes[:transparent]
      "bg-transparent hover:bg-gray-100 text-gray-700"
    when themes[:dark]
      "bg-gray-800 text-white shadow-sm hover:bg-gray-900"
    else
      "bg-white border border-gray-300 shadow-sm hover:bg-gray-100"
    end
  end

  def style_button(variant, theme)
    base = "rounded text-center font-sans font-normal outline-none leading-normal cursor-pointer transition ease-in-out duration-200 font-medium"

    case variant
    when "large"
      "px-5 py-4 text-lg #{base} #{theme}"
    when "small"
      "py-2 px-4 text-sm #{base} #{theme}"
    when "expanded"
      "p-3 w-full block #{base} #{theme}"
    else
      "px-5 py-2 text-base #{base} #{theme}"
    end
  end

  def profile_image(user, options={})
    size = case options[:size]
    when "large"
      "w-20 h-20"
    when "medium"
      "w-14 h-14"
    else
      "w-10 h-10"
    end

    classes = "#{size} flex-skrink-0 rounded-full
    border-2 border-white"

    if user.profile_image.attached?
      image_tag user.profile_image, class: classes
    else
      image_tag "https://cdn.vectorstock.com/i/1000v/33/51/person-gray-photo-placeholder-little-boy-vector-22863351.jpg",
      class: classes
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_profile_helper.rb
module UserProfileHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full antialiased">
  <%= render "shared/head" %>

  <body class="font-sans font-normal leading-normal text-gray-800 bg-white flex flex-col min-h-screen ">

    <header>
      <%= render "shared/flash_notice" %>
      <%= render "shared/navbar" %>
    </header>

    <div class="flex flex-1">
      <div class="flex flex-col w-1/9 bg-gray-200 p-4 rounded-lg mx-6 items-center">
        <% if user_signed_in? %>
          <p class="mb-4">Side Bar Things</p>
          <div class="mb-4 w-10 h-10">
            <%= link_to user_profile_path(current_user) do %>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-full h-full">
                <path fill-rule="evenodd" d="M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0Zm-5.5-2.5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0ZM10 12a5.99 5.99 0 0 0-4.793 2.39A6.483 6.483 0 0 0 10 16.5a6.483 6.483 0 0 0 4.793-2.11A5.99 5.99 0 0 0 10 12Z" clip-rule="evenodd" />
              </svg>
            <% end %>
          </div>
          <%= link_to root_path do %>
            <div class="mb-4 w-10 h-10">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-full h-full">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 18v-5.25m0 0a6.01 6.01 0 0 0 1.5-.189m-1.5.189a6.01 6.01 0 0 1-1.5-.189m3.75 7.478a12.06 12.06 0 0 1-4.5 0m3.75 2.383a14.406 14.406 0 0 1-3 0M14.25 18v-.192c0-.983.658-1.823 1.508-2.316a7.5 7.5 0 1 0-7.517 0c.85.493 1.509 1.333 1.509 2.316V18" />
              </svg>
            </div>
          <% end %>
        <%else%>
          <p> You have no power here! </p>
        <%end%>
      </div>
      
      <main class="flex-grow container mx-auto px-4">
        <div class="grid grid-cols-4 gap-4">
          <div class="col-span-2">
            <%= content_for?(:content) ? yield(:content) : yield %>
          </div>
        </div>
      </main>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html class="h-full antialiased">
    <%= render "shared/head" %>

    <body class="font-sans font-normal leading-normal text-gray-800 bg-white flex flex-col
    min-h-screen">

        <header>
            <%= render "shared/flash_notice" %>
        </header>

        <main>
            <%= content_for?(:content) ? yield(:content) : yield %>
        </main>
    </body>
</html>

app/views/posts/_form.html.erb
<% if user_signed_in? %>
  <%= turbo_frame_tag :body do %>
      <%= form_with model: @post, url: (@post.persisted? ? post_path(@post) : posts_path), 
        local: true, 
        method: (@post.persisted? ? :patch : :post) do |form| %>
      <% if flash[:post_errors] %>
        <div class="bg-red-50 text-red-500 px-3 py-2 font-medium
        rounded-lg mt-3 mx-3">
          <ul>
            <% flash[:post_errors].each do |error| %>
              <li><%= error %> <li> 
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form.label :body, class: "hidden" %>
      <%= form.text_area :body, class: "border border-black border-t-0
      border-x-0 mb-6 px-6 pt-6 block w-full border-gray-200 rounded", 
      placeholder: "Write here!" %>
      <div class="flex justify-end">
        <%= form.submit (@post.persisted? ? "Update Post!" : "Post!"), 
        class: button_class(theme: "primary") %>
      </div>
    <% end %>
  <% end %>
<% else %>
    <p> You are not logged in! </p>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id(post) %>"class="flex flex-col rounded-lg mt-6 py-4 px-4 border border-black">
<%= turbo_frame_tag :body do %>
    <%= post.body %>
<% end %>
<% if user_signed_in? %>
    <div class="flex flex-row justify-between pt-10">
        <div class="space-y-3">
            <p><%= profile_image(post.user)%></p>
            <p><%= post.user.name %></p>
        </div>
            <% if user_signed_in? && current_user == post.user %>
                <div class="w-5 h-5">
                <%= button_to edit_post_path(post), method: :get,
                attribute: :body, 
                class: "inline-flex items-center" do %>
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="w-full h-full">
                    <path d="M13.488 2.513a1.75 1.75 0 0 0-2.475 0L6.75 6.774a2.75 2.75 0 0 0-.596.892l-.848 2.047a.75.75 0 0 0 .98.98l2.047-.848a2.75 2.75 0 0 0 .892-.596l4.261-4.262a1.75 1.75 0 0 0 0-2.474Z" />
                    <path d="M4.75 3.5c-.69 0-1.25.56-1.25 1.25v6.5c0 .69.56 1.25 1.25 1.25h6.5c.69 0 1.25-.56 1.25-1.25V9A.75.75 0 0 1 14 9v2.25A2.75 2.75 0 0 1 11.25 14h-6.5A2.75 2.75 0 0 1 2 11.25v-6.5A2.75 2.75 0 0 1 4.75 2H7a.75.75 0 0 1 0 1.5H4.75Z" />
                    </svg>
                <% end %>
                </div>
                <div class="w-5 h-5">
                <%= button_to post_path(post), method: :delete,
                form: { data: { turbo_confirm: "Are you sure?" }} do %>
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="w-full h-full">
                    <path fill-rule="evenodd" d="M5 3.25V4H2.75a.75.75 0 0 0 0 1.5h.3l.815 8.15A1.5 1.5 0 0 0 5.357 15h5.285a1.5 1.5 0 0 0 1.493-1.35l.815-8.15h.3a.75.75 0 0 0 0-1.5H11v-.75A2.25 2.25 0 0 0 8.75 1h-1.5A2.25 2.25 0 0 0 5 3.25Zm2.25-.75a.75.75 0 0 0-.75.75V4h3v-.75a.75.75 0 0 0-.75-.75h-1.5ZM6.05 6a.75.75 0 0 1 .787.713l.275 5.5a.75.75 0 0 1-1.498.075l-.275-5.5A.75.75 0 0 1 6.05 6Zm3.9 0a.75.75 0 0 1 .712.787l-.275 5.5a.75.75 0 0 1-1.498-.075l.275-5.5a.75.75 0 0 1 .786-.711Z" clip-rule="evenodd" />
                    </svg>
                <% end %>
                </div>
            <% end %>
    </div>
<% else %>
    <p>-</p>
<% end %>
</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.prepend "posts" %>
    <%= render "post", post: @post %>
<% end %>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form', post: @post %>
<%= link_to 'Back', posts_path, class: 'btn btn-secondary' %>

app/views/posts/index.html.erb
<div class=" flex flex-col content-center ">
  <% if user_signed_in? %>
    <%= render "form" %>
  <% end %>
  <div class="m-top-6">
    <%= turbo_frame_tag "posts" do %>
      <div id= "posts">
        <%= render @posts %>
      </div>
    <% end %>
  </div>
</div>
<div class="flex flex-col">
  <% if user_signed_in? %>
    <p>
      Signed in as: <%= current_user.name %>
    </p>
    <div class="pt-4 pb-4">
    <%= button_to "Sign Out", destroy_user_session_path, 
    method: :delete, class: button_class(theme: "primary"), 
    data: {turbo: false} %>
    </div>
  <% else %>
    <div class="pt-4">
    <%= link_to "Sign in", new_user_session_path, 
    class: button_class(theme: "primary") %>
    </div>
  <% end %>
</div>

app/views/shared/_flash_notice.html.erb
<% unless flash[:post_errors] %>
  <% flash.each do |type, message| %>
    <div class="<%= flash_classes(type) %>">
      <%= message %>
    </div>
  <% end %>
<% end %>

app/views/shared/_head.html.erb
 <head>
  <title>
    <%= content_for?(:title) ? yield(:title) : "Mini-Muni" %>
  </title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag  'application', 'data-turbolinks-track': 'reload' %>
  <%#= javascript_include_tag "application", defer: true %>
  <%#= javascript_include_tag 'https://js.stripe.com/v3/', 'data-turbolinks-track': 'reload' %>
</head>

app/views/shared/_navbar.html.erb
<nav class="flex flex-wrap items-center justify-between py-3 text-gray-700 bg-white container mx-auto px-4 <%= nav_classes %>" data-controller="nav">
  <div class="flex items-center mr-6 flex-no-shrink">
    <%= link_to root_path, class:"link text-xl tracking-tight font-black" do %>
      <span class="sr-only">Add your app name here</span>
      <%# Remove this logo and add your own %>
      <svg fill="none" class="w-9 h-9" height="512" viewBox="0 0 512 512" width="512" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><linearGradient id="a" gradientUnits="userSpaceOnUse" x1="56" x2="463" y1="46" y2="465"><stop offset="0" stop-color="#8038ed"/><stop offset="1" stop-color="#3a0092"/></linearGradient><path d="m0 0h512v512h-512z" fill="#fff"/><rect fill="url(#a)" height="512" rx="110" width="512"/><g stroke="#fff"><circle cx="190" cy="302" r="79.5" stroke-opacity=".9" stroke-width="25"/><circle cx="254" cy="377" r="34" stroke-opacity=".8" stroke-width="10"/><circle cx="282" cy="227" r="106" stroke-width="50"/></g></svg>
    <% end %>
  </div>
  <div class="block lg:hidden">
    <%# Mobile nav toggle %>
    <button class="flex items-center p-2 -mr-1 rounded-lg focus:bg-gray-100" data-action="click->nav#toggleMenu touch->nav#toggleMenu">
      <svg class="stroke-current text-gray-500 w-7 h-7" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><title>Menu</title><g fill="none"><path d="M4 6h16M4 12h8m-8 6h16" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></g></svg>
    </button>
  </div>
  <div class="items-center w-full text-center lg:flex-1 lg:flex lg:text-left pt-2 lg:pt-0 hidden" data-nav-target="menu">
    <div class="lg:flex-grow">
      <%= link_to "Basic Link", "#", class: "p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %>
    </div>
    <div class="items-center block w-full mt-2 text-center lg:flex lg:flex-row lg:flex-1 lg:mt-0 lg:text-left lg:justify-end">
      <div><%# More links can go here %></div>
      <% if user_signed_in? %>
        <%= link_to "Edit account", edit_user_registration_path, class: "p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %>
        <%= button_to "Log out", destroy_user_session_path, method: :delete, class:"p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %>
      <% else %>
        <%= link_to "Sign in", new_user_session_path, class:"p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %>
        <%= link_to "Sign up", new_user_registration_path, class:"p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block lg:ml-2" %>

        <span class="h-5 w-px bg-gray-200 mx-3"></span>

        <%= link_to "https://github.com/justalever/kickoff_tailwind", target: :_blank, class: "group lg:ml-2 flex justify-center" do %>
          <svg class="fill-current text-gray-400 group-hover:text-gray-600" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>

app/views/user_profile/show.html.erb
<div class="flex items-center justify-between">
    <div class="flex-1 items-center">
        <%= profile_image(@profile, size: "large") %> 
    </div>
    <div class="flex-1">
        <h1><%= @profile.name %>`s profile</h1>
    </div>
    <div>
        <%= link_to "Edit Profile", edit_user_registration_path,
        class: "inline-flex justify-center items-center px-5 py-2 rounded-md border ring-4
        focus:ring-sky-50 ring-transparent hover:ring-sky-50 hover:border-gray-300" if current_user %>
    </div>
</div>
<div>
    <%= render collection: @profile.posts, partial: "posts/post" %>
</div>